/**
 * 中国省市区级联数据
 *
 * 覆盖 34 个省/直辖市/自治区，每个省下包含主要地级市。
 * 数据结构为两级联动：省份 → 城市。
 */

export interface Region {
  label: string;
  value: string; // slug 格式
  children?: Region[];
}

export const regions: Region[] = [
  // ── 华北 ──
  {
    label: "北京市",
    value: "beijing",
    children: [
      { label: "东城区", value: "dongcheng" },
      { label: "西城区", value: "xicheng" },
      { label: "朝阳区", value: "chaoyang" },
      { label: "丰台区", value: "fengtai" },
      { label: "海淀区", value: "haidian" },
      { label: "顺义区", value: "shunyi" },
      { label: "通州区", value: "tongzhou" },
      { label: "大兴区", value: "daxing" },
      { label: "房山区", value: "fangshan" },
      { label: "昌平区", value: "changping" },
    ],
  },
  {
    label: "天津市",
    value: "tianjin",
    children: [
      { label: "和平区", value: "heping" },
      { label: "河东区", value: "hedong" },
      { label: "河西区", value: "hexi" },
      { label: "南开区", value: "nankai" },
      { label: "河北区", value: "hebei" },
      { label: "红桥区", value: "hongqiao" },
      { label: "滨海新区", value: "binhaixinqu" },
      { label: "东丽区", value: "dongli" },
      { label: "西青区", value: "xiqing" },
      { label: "津南区", value: "jinnan" },
      { label: "北辰区", value: "beichen" },
      { label: "武清区", value: "wuqing" },
    ],
  },
  {
    label: "河北省",
    value: "hebei",
    children: [
      { label: "石家庄市", value: "shijiazhuang" },
      { label: "唐山市", value: "tangshan" },
      { label: "秦皇岛市", value: "qinhuangdao" },
      { label: "邯郸市", value: "handan" },
      { label: "保定市", value: "baoding" },
      { label: "张家口市", value: "zhangjiakou" },
      { label: "承德市", value: "chengde" },
      { label: "廊坊市", value: "langfang" },
      { label: "沧州市", value: "cangzhou" },
      { label: "衡水市", value: "hengshui" },
      { label: "邢台市", value: "xingtai" },
    ],
  },
  {
    label: "山西省",
    value: "shanxi",
    children: [
      { label: "太原市", value: "taiyuan" },
      { label: "大同市", value: "datong" },
      { label: "阳泉市", value: "yangquan" },
      { label: "长治市", value: "changzhi" },
      { label: "晋城市", value: "jincheng" },
      { label: "朔州市", value: "shuozhou" },
      { label: "晋中市", value: "jinzhong" },
      { label: "运城市", value: "yuncheng" },
      { label: "忻州市", value: "xinzhou" },
      { label: "临汾市", value: "linfen" },
      { label: "吕梁市", value: "lvliang" },
    ],
  },
  {
    label: "内蒙古自治区",
    value: "neimenggu",
    children: [
      { label: "呼和浩特市", value: "huhehaote" },
      { label: "包头市", value: "baotou" },
      { label: "乌海市", value: "wuhai" },
      { label: "赤峰市", value: "chifeng" },
      { label: "通辽市", value: "tongliao" },
      { label: "鄂尔多斯市", value: "eerduosi" },
      { label: "呼伦贝尔市", value: "hulunbeier" },
      { label: "巴彦淖尔市", value: "bayannaoer" },
    ],
  },
  // ── 东北 ──
  {
    label: "辽宁省",
    value: "liaoning",
    children: [
      { label: "沈阳市", value: "shenyang" },
      { label: "大连市", value: "dalian" },
      { label: "鞍山市", value: "anshan" },
      { label: "抚顺市", value: "fushun" },
      { label: "本溪市", value: "benxi" },
      { label: "丹东市", value: "dandong" },
      { label: "锦州市", value: "jinzhou" },
      { label: "营口市", value: "yingkou" },
      { label: "阜新市", value: "fuxin" },
      { label: "辽阳市", value: "liaoyang" },
      { label: "盘锦市", value: "panjin" },
      { label: "铁岭市", value: "tieling" },
    ],
  },
  {
    label: "吉林省",
    value: "jilin",
    children: [
      { label: "长春市", value: "changchun" },
      { label: "吉林市", value: "jilin" },
      { label: "四平市", value: "siping" },
      { label: "辽源市", value: "liaoyuan" },
      { label: "通化市", value: "tonghua" },
      { label: "白山市", value: "baishan" },
      { label: "松原市", value: "songyuan" },
      { label: "白城市", value: "baicheng" },
    ],
  },
  {
    label: "黑龙江省",
    value: "heilongjiang",
    children: [
      { label: "哈尔滨市", value: "haerbin" },
      { label: "齐齐哈尔市", value: "qiqihaer" },
      { label: "牡丹江市", value: "mudanjiang" },
      { label: "佳木斯市", value: "jiamusi" },
      { label: "大庆市", value: "daqing" },
      { label: "鸡西市", value: "jixi" },
      { label: "双鸭山市", value: "shuangyashan" },
      { label: "伊春市", value: "yichun" },
      { label: "七台河市", value: "qitaihe" },
      { label: "鹤岗市", value: "hegang" },
      { label: "黑河市", value: "heihe" },
      { label: "绥化市", value: "suihua" },
    ],
  },
  // ── 华东 ──
  {
    label: "上海市",
    value: "shanghai",
    children: [
      { label: "黄浦区", value: "huangpu" },
      { label: "徐汇区", value: "xuhui" },
      { label: "长宁区", value: "changning" },
      { label: "静安区", value: "jingan" },
      { label: "普陀区", value: "putuo" },
      { label: "虹口区", value: "hongkou" },
      { label: "杨浦区", value: "yangpu" },
      { label: "浦东新区", value: "pudong" },
      { label: "闵行区", value: "minhang" },
      { label: "宝山区", value: "baoshan" },
      { label: "嘉定区", value: "jiading" },
      { label: "松江区", value: "songjiang" },
      { label: "青浦区", value: "qingpu" },
      { label: "奉贤区", value: "fengxian" },
      { label: "金山区", value: "jinshan" },
      { label: "崇明区", value: "chongming" },
    ],
  },
  {
    label: "江苏省",
    value: "jiangsu",
    children: [
      { label: "南京市", value: "nanjing" },
      { label: "苏州市", value: "suzhou" },
      { label: "无锡市", value: "wuxi" },
      { label: "常州市", value: "changzhou" },
      { label: "南通市", value: "nantong" },
      { label: "徐州市", value: "xuzhou" },
      { label: "扬州市", value: "yangzhou" },
      { label: "盐城市", value: "yancheng" },
      { label: "镇江市", value: "zhenjiang" },
      { label: "泰州市", value: "taizhou" },
      { label: "淮安市", value: "huaian" },
      { label: "连云港市", value: "lianyungang" },
      { label: "宿迁市", value: "suqian" },
    ],
  },
  {
    label: "浙江省",
    value: "zhejiang",
    children: [
      { label: "杭州市", value: "hangzhou" },
      { label: "宁波市", value: "ningbo" },
      { label: "温州市", value: "wenzhou" },
      { label: "嘉兴市", value: "jiaxing" },
      { label: "湖州市", value: "huzhou" },
      { label: "绍兴市", value: "shaoxing" },
      { label: "金华市", value: "jinhua" },
      { label: "衢州市", value: "quzhou" },
      { label: "台州市", value: "taizhou" },
      { label: "丽水市", value: "lishui" },
      { label: "舟山市", value: "zhoushan" },
    ],
  },
  {
    label: "安徽省",
    value: "anhui",
    children: [
      { label: "合肥市", value: "hefei" },
      { label: "芜湖市", value: "wuhu" },
      { label: "蚌埠市", value: "bengbu" },
      { label: "淮南市", value: "huainan" },
      { label: "马鞍山市", value: "maanshan" },
      { label: "安庆市", value: "anqing" },
      { label: "黄山市", value: "huangshan" },
      { label: "滁州市", value: "chuzhou" },
      { label: "阜阳市", value: "fuyang" },
      { label: "宿州市", value: "suzhou" },
      { label: "六安市", value: "liuan" },
      { label: "宣城市", value: "xuancheng" },
      { label: "铜陵市", value: "tongling" },
    ],
  },
  {
    label: "福建省",
    value: "fujian",
    children: [
      { label: "福州市", value: "fuzhou" },
      { label: "厦门市", value: "xiamen" },
      { label: "泉州市", value: "quanzhou" },
      { label: "漳州市", value: "zhangzhou" },
      { label: "莆田市", value: "putian" },
      { label: "龙岩市", value: "longyan" },
      { label: "三明市", value: "sanming" },
      { label: "南平市", value: "nanping" },
      { label: "宁德市", value: "ningde" },
    ],
  },
  {
    label: "江西省",
    value: "jiangxi",
    children: [
      { label: "南昌市", value: "nanchang" },
      { label: "九江市", value: "jiujiang" },
      { label: "景德镇市", value: "jingdezhen" },
      { label: "萍乡市", value: "pingxiang" },
      { label: "赣州市", value: "ganzhou" },
      { label: "上饶市", value: "shangrao" },
      { label: "吉安市", value: "jian" },
      { label: "抚州市", value: "fuzhou" },
      { label: "宜春市", value: "yichun" },
      { label: "新余市", value: "xinyu" },
      { label: "鹰潭市", value: "yingtan" },
    ],
  },
  {
    label: "山东省",
    value: "shandong",
    children: [
      { label: "济南市", value: "jinan" },
      { label: "青岛市", value: "qingdao" },
      { label: "淄博市", value: "zibo" },
      { label: "枣庄市", value: "zaozhuang" },
      { label: "东营市", value: "dongying" },
      { label: "烟台市", value: "yantai" },
      { label: "潍坊市", value: "weifang" },
      { label: "济宁市", value: "jining" },
      { label: "泰安市", value: "taian" },
      { label: "威海市", value: "weihai" },
      { label: "日照市", value: "rizhao" },
      { label: "临沂市", value: "linyi" },
      { label: "德州市", value: "dezhou" },
      { label: "聊城市", value: "liaocheng" },
      { label: "滨州市", value: "binzhou" },
      { label: "菏泽市", value: "heze" },
    ],
  },
  // ── 华中 ──
  {
    label: "河南省",
    value: "henan",
    children: [
      { label: "郑州市", value: "zhengzhou" },
      { label: "洛阳市", value: "luoyang" },
      { label: "开封市", value: "kaifeng" },
      { label: "南阳市", value: "nanyang" },
      { label: "安阳市", value: "anyang" },
      { label: "新乡市", value: "xinxiang" },
      { label: "许昌市", value: "xuchang" },
      { label: "平顶山市", value: "pingdingshan" },
      { label: "焦作市", value: "jiaozuo" },
      { label: "信阳市", value: "xinyang" },
      { label: "周口市", value: "zhoukou" },
      { label: "驻马店市", value: "zhumadian" },
      { label: "商丘市", value: "shangqiu" },
      { label: "漯河市", value: "luohe" },
    ],
  },
  {
    label: "湖北省",
    value: "hubei",
    children: [
      { label: "武汉市", value: "wuhan" },
      { label: "宜昌市", value: "yichang" },
      { label: "襄阳市", value: "xiangyang" },
      { label: "荆州市", value: "jingzhou" },
      { label: "黄冈市", value: "huanggang" },
      { label: "十堰市", value: "shiyan" },
      { label: "孝感市", value: "xiaogan" },
      { label: "咸宁市", value: "xianning" },
      { label: "黄石市", value: "huangshi" },
      { label: "鄂州市", value: "ezhou" },
      { label: "荆门市", value: "jingmen" },
      { label: "随州市", value: "suizhou" },
    ],
  },
  {
    label: "湖南省",
    value: "hunan",
    children: [
      { label: "长沙市", value: "changsha" },
      { label: "株洲市", value: "zhuzhou" },
      { label: "湘潭市", value: "xiangtan" },
      { label: "衡阳市", value: "hengyang" },
      { label: "岳阳市", value: "yueyang" },
      { label: "常德市", value: "changde" },
      { label: "张家界市", value: "zhangjiajie" },
      { label: "益阳市", value: "yiyang" },
      { label: "郴州市", value: "chenzhou" },
      { label: "永州市", value: "yongzhou" },
      { label: "怀化市", value: "huaihua" },
      { label: "娄底市", value: "loudi" },
      { label: "邵阳市", value: "shaoyang" },
    ],
  },
  // ── 华南 ──
  {
    label: "广东省",
    value: "guangdong",
    children: [
      { label: "广州市", value: "guangzhou" },
      { label: "深圳市", value: "shenzhen" },
      { label: "佛山市", value: "foshan" },
      { label: "东莞市", value: "dongguan" },
      { label: "珠海市", value: "zhuhai" },
      { label: "中山市", value: "zhongshan" },
      { label: "惠州市", value: "huizhou" },
      { label: "汕头市", value: "shantou" },
      { label: "江门市", value: "jiangmen" },
      { label: "湛江市", value: "zhanjiang" },
      { label: "肇庆市", value: "zhaoqing" },
      { label: "茂名市", value: "maoming" },
      { label: "揭阳市", value: "jieyang" },
      { label: "梅州市", value: "meizhou" },
      { label: "清远市", value: "qingyuan" },
      { label: "韶关市", value: "shaoguan" },
      { label: "潮州市", value: "chaozhou" },
      { label: "河源市", value: "heyuan" },
      { label: "阳江市", value: "yangjiang" },
      { label: "云浮市", value: "yunfu" },
      { label: "汕尾市", value: "shanwei" },
    ],
  },
  {
    label: "广西壮族自治区",
    value: "guangxi",
    children: [
      { label: "南宁市", value: "nanning" },
      { label: "柳州市", value: "liuzhou" },
      { label: "桂林市", value: "guilin" },
      { label: "梧州市", value: "wuzhou" },
      { label: "北海市", value: "beihai" },
      { label: "玉林市", value: "yulin" },
      { label: "百色市", value: "baise" },
      { label: "钦州市", value: "qinzhou" },
    ],
  },
  {
    label: "海南省",
    value: "hainan",
    children: [
      { label: "海口市", value: "haikou" },
      { label: "三亚市", value: "sanya" },
      { label: "儋州市", value: "danzhou" },
      { label: "琼海市", value: "qionghai" },
    ],
  },
  // ── 西南 ──
  {
    label: "重庆市",
    value: "chongqing",
    children: [
      { label: "渝中区", value: "yuzhong" },
      { label: "江北区", value: "jiangbei" },
      { label: "南岸区", value: "nanan" },
      { label: "渝北区", value: "yubei" },
      { label: "沙坪坝区", value: "shapingba" },
      { label: "九龙坡区", value: "jiulongpo" },
      { label: "大渡口区", value: "dadukou" },
      { label: "巴南区", value: "banan" },
      { label: "北碚区", value: "beibei" },
      { label: "万州区", value: "wanzhou" },
      { label: "涪陵区", value: "fuling" },
    ],
  },
  {
    label: "四川省",
    value: "sichuan",
    children: [
      { label: "成都市", value: "chengdu" },
      { label: "绵阳市", value: "mianyang" },
      { label: "德阳市", value: "deyang" },
      { label: "宜宾市", value: "yibin" },
      { label: "南充市", value: "nanchong" },
      { label: "泸州市", value: "luzhou" },
      { label: "达州市", value: "dazhou" },
      { label: "乐山市", value: "leshan" },
      { label: "自贡市", value: "zigong" },
      { label: "内江市", value: "neijiang" },
      { label: "遂宁市", value: "suining" },
      { label: "广安市", value: "guangan" },
      { label: "攀枝花市", value: "panzhihua" },
    ],
  },
  {
    label: "贵州省",
    value: "guizhou",
    children: [
      { label: "贵阳市", value: "guiyang" },
      { label: "遵义市", value: "zunyi" },
      { label: "六盘水市", value: "liupanshui" },
      { label: "安顺市", value: "anshun" },
      { label: "毕节市", value: "bijie" },
      { label: "铜仁市", value: "tongren" },
    ],
  },
  {
    label: "云南省",
    value: "yunnan",
    children: [
      { label: "昆明市", value: "kunming" },
      { label: "大理白族自治州", value: "dali" },
      { label: "丽江市", value: "lijiang" },
      { label: "曲靖市", value: "qujing" },
      { label: "玉溪市", value: "yuxi" },
      { label: "保山市", value: "baoshan" },
      { label: "昭通市", value: "zhaotong" },
      { label: "普洱市", value: "puer" },
      { label: "临沧市", value: "lincang" },
    ],
  },
  {
    label: "西藏自治区",
    value: "xizang",
    children: [
      { label: "拉萨市", value: "lasa" },
      { label: "日喀则市", value: "rikaze" },
      { label: "昌都市", value: "changdu" },
      { label: "林芝市", value: "linzhi" },
    ],
  },
  // ── 西北 ──
  {
    label: "陕西省",
    value: "shaanxi",
    children: [
      { label: "西安市", value: "xian" },
      { label: "宝鸡市", value: "baoji" },
      { label: "咸阳市", value: "xianyang" },
      { label: "渭南市", value: "weinan" },
      { label: "延安市", value: "yanan" },
      { label: "汉中市", value: "hanzhong" },
      { label: "榆林市", value: "yulin" },
      { label: "安康市", value: "ankang" },
      { label: "商洛市", value: "shangluo" },
    ],
  },
  {
    label: "甘肃省",
    value: "gansu",
    children: [
      { label: "兰州市", value: "lanzhou" },
      { label: "天水市", value: "tianshui" },
      { label: "白银市", value: "baiyin" },
      { label: "武威市", value: "wuwei" },
      { label: "酒泉市", value: "jiuquan" },
      { label: "嘉峪关市", value: "jiayuguan" },
      { label: "张掖市", value: "zhangye" },
    ],
  },
  {
    label: "青海省",
    value: "qinghai",
    children: [
      { label: "西宁市", value: "xining" },
      { label: "海东市", value: "haidong" },
      { label: "海西蒙古族藏族自治州", value: "haixi" },
    ],
  },
  {
    label: "宁夏回族自治区",
    value: "ningxia",
    children: [
      { label: "银川市", value: "yinchuan" },
      { label: "石嘴山市", value: "shizuishan" },
      { label: "吴忠市", value: "wuzhong" },
      { label: "固原市", value: "guyuan" },
      { label: "中卫市", value: "zhongwei" },
    ],
  },
  {
    label: "新疆维吾尔自治区",
    value: "xinjiang",
    children: [
      { label: "乌鲁木齐市", value: "wulumuqi" },
      { label: "克拉玛依市", value: "kelamayi" },
      { label: "吐鲁番市", value: "tulufan" },
      { label: "哈密市", value: "hami" },
      { label: "昌吉回族自治州", value: "changji" },
      { label: "伊犁哈萨克自治州", value: "yili" },
      { label: "喀什地区", value: "kashi" },
      { label: "阿克苏地区", value: "akesu" },
    ],
  },
  // ── 港澳台 ──
  {
    label: "香港特别行政区",
    value: "hongkong",
    children: [
      { label: "中西区", value: "zhongxi" },
      { label: "湾仔区", value: "wanzai" },
      { label: "东区", value: "dongqu" },
      { label: "南区", value: "nanqu" },
      { label: "油尖旺区", value: "youjianwang" },
      { label: "深水埗区", value: "shenshuibu" },
      { label: "九龙城区", value: "jiulongcheng" },
      { label: "黄大仙区", value: "huangdaxian" },
      { label: "观塘区", value: "guantang" },
    ],
  },
  {
    label: "澳门特别行政区",
    value: "macau",
    children: [
      { label: "花地玛堂区", value: "huadima" },
      { label: "圣安多尼堂区", value: "shenganduoni" },
      { label: "大堂区", value: "datang" },
      { label: "望德堂区", value: "wangde" },
      { label: "风顺堂区", value: "fengshun" },
    ],
  },
  {
    label: "台湾省",
    value: "taiwan",
    children: [
      { label: "台北市", value: "taibei" },
      { label: "新北市", value: "xinbei" },
      { label: "桃园市", value: "taoyuan" },
      { label: "台中市", value: "taizhong" },
      { label: "台南市", value: "tainan" },
      { label: "高雄市", value: "gaoxiong" },
    ],
  },
];

/**
 * 根据省份 value 查找城市列表
 */
export function getCitiesByProvince(provinceValue: string): Region[] {
  const province = regions.find((r) => r.value === provinceValue);
  return province?.children ?? [];
}
