created: 2026-07-11T06:18:21.293Z
updated: 2026-07-11T06:18:23.296Z
update_count: 7
last_field: note
git_commit: "5280714"
git_branch: main
children:
  - content-data
  - local-files
  - next-app
  - observability
  - postgres
  - static-fallback
  - users
