created: 2026-07-11T06:18:43.479Z
updated: 2026-07-11T06:18:44.846Z
update_count: 2
last_field: diagram
kind: nested-class
title: content-data
children:
  - current-blog
  - current-images
  - current-stores
  - mock-data
  - prisma
  - self-api
parentPath: []
